apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: rocketchat
  labels:
    run: mongodb
  name: mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    protocol: TCP
    targetPort: 27017
  clusterIP: None
  selector:
    run: mongodb
  type: ClusterIP
status:
  loadBalancer: {}
