apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    run: mongo
  name: mongo
  namespace: rocketchat
spec:
  replicas: 1
  selector:
    run: mongo
  template:
    metadata:
      labels:
        run: mongo
    spec:
      volumes:
        - name: mongodata
          persistentVolumeClaim:
           claimName: mongo-pvc
      containers:
      - image: mongo
        command:
          - mongod
          - --replSet
          - rs0
        name: mongo
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongodata
            mountPath: /data/db
        
