apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  nfs:
    server: 172.18.1.207
    path: /share/nfs/rocketchat/mongodb
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 3Gi
  
