apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
#      securityContext:
#        supplementalGroups: [65534] 
#      serviceAccountName: mgrpls
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongodb-rocketchat-data-claim
      containers:
        - image: angelodias/mongodb:latest
          name: mongod
          command:
            - mongod
            - --replSet
            - "rs0"
            - --bind_ip
            - 0.0.0.0

          env:
            - name: MONGO_INITDB_DATABASE
              value: rocketchat 
  

          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
