apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /export/mounts/sdf1
    server: 172.17.1.199
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
