apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
spec:
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /export/mounts/sdc1
    server: 172.17.1.199
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
