apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
#  namespace: rocketchat   
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
