apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-rocketchat-data-claim
  namespace: rocketchat
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
