apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rocketchat
  name: rocketchat
  namespace: rocketchat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rocketchat
    spec:
      containers:
        - name: rocketchat
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:mongodb@mongodb:27017/rocketchat
          image: rocket.chat:latest
          imagePullPolicy: Always
          name: rocketchat
          ports:
            - containerPort: 3000
